name: Node.js Package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Run Build
    - run: npm install
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: app.json
        path: .sote/app.json
