name: Node.js Package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Run Build
    - run: npm install && npm run build
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_PASSWORD }}
        password: ${{ secrets.REMOTE_USER }}
        port: 22
        script: npm run start
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: app.json
    #     path: .sote/app.json
